## Docker compose para instalacion de Oraclec-Apex-Ords## Docker compose para instalacion de Oraclec-Apex-Ords
services:
  # --- CONTENEDOR DE LA BASE DE DATOS ORACLE ---
  oracle-db:
    image: josmacpac/oracle19c-apex:v1
    container_name: oracle19c-apex
    restart: always
    environment:
      - ORACLE_PWD=Password123$
      - TZ=America/Mexico_City
      - ORACLE_EDITION=enterprise
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
    ports:
      - "32122:1521"
    volumes:
      - ./oradata:/opt/oracle/oradata # Persistencia de datos 
      - ./apex/apex:/home/oracle/apex_install # Instalador de APEX 
      - ./scripts:/home/oracle/scripts
    shm_size: '2gb'       # Crucial para evitar errores de memoria en Oracle
    deploy:
      resources:
        limits:
          memory: 5G      # RAM máxima recomendada
          cpus: '2.0'
    networks:
      - oracle_network

  # --- CONTENEDOR DE ORDS (APEX WEB) ---
  ords-server:
    build:
      context: ./ords          # Carpeta donde está tu Dockerfile de ORDS
    container_name: ords-server
    restart: always
    stdin_open: true 
    tty: true
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    environment:
      - ORACLE_HOST=oracle19c-apex
      - ORACLE_PORT=1521
      # CAMBIO IMPORTANTE: Apuntar a la PDB para que ORDS encuentre APEX
      - ORACLE_SERVICE=ORCLPDB1  
      - ORACLE_PWD=Password123$
      - APEX_PUBLIC_USER_PASSWORD=Password123$
      - APEX_LISTENER_PASSWORD=Password123$
      - APEX_REST_PASSWORD=Password123$
    volumes:
      # Mapeo para las imágenes de APEX 20.1
      - ./apex/apex/images:/ords/apex-images
      # Persistencia de la configuración nueva
      - ./ords_config:/opt/ords 
    networks:
      - oracle_network

networks:
  oracle_network:
    driver: bridge
