## Docker compose para instalacion de Oraclec-Apex-Ords## Docker compose para instalacion de Oraclec-Apex-Ords
services:
  # --- CONTENEDOR DE LA BASE DE DATOS ORACLE ---
  oracle-db:
    image: josmacpac/oracle19c-apex:v1
    container_name: oracle19c-apex
    restart: always
    environment:
      - ORACLE_PWD=Password123$
      - TZ=America/Mexico_City
      - ORACLE_EDITION=enterprise
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
    ports:
      - "32122:1521"
    volumes:
      - ./oradata:/opt/oracle/oradata # Persistencia de datos 
      - ./apex/apex:/home/oracle/apex_install # Instalador de APEX 
      - ./scripts:/home/oracle/scripts
    shm_size: '2gb'       # Crucial para evitar errores de memoria en Oracle
    deploy:
      resources:
        limits:
          memory: 5G      # RAM máxima recomendada
          cpus: '2.0'
    networks:
      - oracle_network

  # --- CONTENEDOR DE ORDS (APEX WEB) ---
  ords-server:
    image: josmacpac/ords-apex:20.4  # <--- Tu imagen ya registrada
    container_name: ords-server
    restart: always
    stdin_open: true 
    tty: true
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"       # Puerto para entrar a APEX desde el navegador
    environment:
      - ORACLE_HOST=oracle19c-apex
      - ORACLE_PORT=1521
      - ORACLE_SERVICE=ORCLCDB
    networks:
      - oracle_network

networks:
  oracle_network:
    driver: bridge

